// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AnnualReports.Domain.Core.DistDbModels
{

    [Table("GL40200", Schema = "dbo")]
    public class Gl40200
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"SGMTNUMB", Order = 1, TypeName = "smallint")]
        [Index(@"PKGL40200", 1, IsUnique = true, IsClustered = false)]
        [Required]
        [Key]
        [Display(Name = "Sgmtnumb")]
        public short Sgmtnumb { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"SGMNTID", Order = 2, TypeName = "char")]
        [Index(@"PKGL40200", 2, IsUnique = true, IsClustered = false)]
        [Required]
        [MaxLength(67)]
        [StringLength(67)]
        [Key]
        [Display(Name = "Sgmntid")]
        public string Sgmntid { get; set; }

        [Column(@"DSCRIPTN", Order = 3, TypeName = "char")]
        [Required]
        [MaxLength(31)]
        [StringLength(31)]
        [Display(Name = "Dscriptn")]
        public string FundDescription { get; set; }

        [Column(@"SEGCOUNT", Order = 4, TypeName = "int")]
        [Required]
        [Display(Name = "Segcount")]
        public int Segcount { get; set; }

        [Column(@"NOTEINDX", Order = 5, TypeName = "numeric")]
        [Required]
        [Display(Name = "Noteindx")]
        public decimal Noteindx { get; set; }

        [Column(@"DEX_ROW_TS", Order = 6, TypeName = "datetime")]
        [Required]
        [Display(Name = "Dex row ts")]
        public System.DateTime DexRowTs { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"DEX_ROW_ID", Order = 7, TypeName = "int")]
        [Required]
        [Display(Name = "Dex row ID")]
        public int DexRowId { get; set; }

        public Gl40200()
        {
            DexRowTs = System.DateTime.UtcNow;
        }
    }

}
// </auto-generated>
