// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AnnualReports.Domain.Core.GcDbModels
{

    [Table("GL00102", Schema = "dbo")]
    public class Gl00102
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"ACCATNUM", Order = 1, TypeName = "smallint")]
        [Index(@"PKGL00102", 1, IsUnique = true, IsClustered = false)]
        [Required]
        [Key]
        [Display(Name = "Accatnum")]
        public short Accatnum { get; set; }

        [Column(@"ACCATDSC", Order = 2, TypeName = "char")]
        [Required]
        [MaxLength(51)]
        [StringLength(51)]
        [Display(Name = "Accatdsc")]
        public string Accatdsc { get; set; }

        [Column(@"DEX_ROW_TS", Order = 3, TypeName = "datetime")]
        [Required]
        [Display(Name = "Dex row ts")]
        public System.DateTime DexRowTs { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"DEX_ROW_ID", Order = 4, TypeName = "int")]
        [Required]
        [Display(Name = "Dex row ID")]
        public int DexRowId { get; set; }

        public Gl00102()
        {
            DexRowTs = System.DateTime.UtcNow;
        }
    }

}
// </auto-generated>
