// <auto-generated />
namespace AnnualReports.Infrastructure.Core.Migrations.AnnualReportsDb
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddDbSourceToBars : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDbSourceToBars));
        
        string IMigrationMetadata.Id
        {
            get { return "201801211418475_AddDbSourceToBars"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
